export const products = [
  {
    id: 1,
    name: 'Laptop',
    description: 'Powerful laptop with 16GB RAM and 512GB SSD',
    price: 1200,
    image: 'https://example.com/images/laptop.jpg',
    stock: 10,
  },
  {
    id: 2,
    name: 'Monitor',
    description: '27-inch monitor with 4K resolution',
    price: 500,
    image: 'https://example.com/images/monitor.jpg',
    stock: 5,
  },
  {
    id: 3,
    name: 'Keyboard',
    description: 'Mechanical keyboard with RGB lighting',
    price: 80,
    image: 'https://example.com/images/keyboard.jpg',
    stock: 15,
  },
  {
    id: 4,
    name: 'Mouse',
    description: 'Wireless mouse with ergonomic design',
    price: 50,
    image: 'https://example.com/images/mouse.jpg',
    stock: 20,
  },
  {
    id: 5,
    name: 'Headphones',
    description: 'Noise-cancelling headphones with Bluetooth connectivity',
    price: 150,
    image: 'https://example.com/images/headphones.jpg',
    stock: 8,
  },
  {
    id: 6,
    name: 'External Hard Drive',
    description: '1TB external hard drive with USB 3.0',
    price: 100,
    image: 'https://example.com/images/hard-drive.jpg',
    stock: 12,
  },
  {
    id: 7,
    name: 'Webcam',
    description: '1080p webcam with built-in microphone',
    price: 60,
    image: 'https://example.com/images/webcam.jpg',
    stock: 6,
  },
];
